
image: python:3.9

test-docs:
  stage: test
  script:
    - wget https://github.com/jgm/pandoc/releases/download/2.19.2/pandoc-2.19.2-1-amd64.deb
    - dpkg -i pandoc-2.19.2-1-amd64.deb
    - python -m pip install -e ".[dev]"
    - cd docs; make; cd ..
    - mv docs/build/html/ ../public/
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"

pages:
  stage: deploy
  script:
    - wget https://github.com/jgm/pandoc/releases/download/2.19.2/pandoc-2.19.2-1-amd64.deb
    - dpkg -i pandoc-2.19.2-1-amd64.deb
    - python -m pip install --upgrade pip
    - python -m pip install -e ".[dev]"
    - cd docs; make; cd ..
    - mv docs/build/html/ ../public/
  artifacts:
    paths:
    - public
  rules:
    - if: $CI_COMMIT_REF_NAME == "release"

merge-request-pipeline-job:
  stage: test
  script:
    - python -m pip install --upgrade pip
    - python -m pip install ".[dev]"
    - mypy fftarray examples
    - python -m pytest --include-slow
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"

