[project]
name = "fftarray"
# TODO: Make dynamic
version = "0.4"
authors = [
    { name="Stefan Seckmeyer"},
    { name="Gabriel Müller"},
    { name="Christian Struckmann"},
]
description = "A library to manage and effiently implement all complexities around the complex Fast Fourier Transform."
readme = "README.md"
requires-python = ">=3.10"
classifiers = [
    "Programming Language :: Python :: 3",
    # TODO: License
    "Operating System :: OS Independent",
]
dependencies = [
    "numpy>=1.25",
]

[build-system]
build-backend = "hatchling.build"
requires = ["hatchling"]

[project.urls]
Homepage = "https://github.com/pypa/sampleproject"
Issues = "https://github.com/pypa/sampleproject/issues"

[project.optional-dependencies]
"jax" = [
    "jax>=0.4.30"
]
"pyFFTW" = [
    "pyFFTW"
]
"helpers" = [
    "z3-solver",
    "xarray"
]
"dashboards" = [
    "fftarray[helpers]",
    "ipython",
    "bokeh"
]
"dev" = [
    "fftarray[jax, pyFFTW, helpers, dashboards]",
    "mypy>=0.910",
    "pytest",
    "hypothesis",
    "sphinx>=4.2",
    "sphinx_rtd_theme",
    "myst_parser",
    "mistune==0.8.4",
    "m2r2",
    "nbformat",
]

"jaxCuda" = [
    "fftarray[jax]",
    # Disabled as workaround Part 1 for https://github.com/prefix-dev/pixi/issues/1051
    # "jax[cuda12]>=0.4.30"
]

[tool.pixi.tasks]
# test = { cmd = ["pytest", "fftarray"]}
test = { cmd = ["python", "-m", "pytest"]}
test_all = { cmd = ["python", "-m", "pytest", "--include-slow"]}
mypy = { cmd = ["mypy", "fftarray"]}
check = { cmd = [], depends-on = ["mypy", "test"]}

[tool.pixi.project]
channels = ["conda-forge"]
platforms = ["linux-64", "linux-aarch64", "osx-arm64", "osx-64", "win-64"]

[tool.pixi.pypi-dependencies]
fftarray = { path = ".", editable = true }

[tool.pixi.feature.jaxCuda]
# Disabled as workaround Part 2 for https://github.com/prefix-dev/pixi/issues/1051
# platforms = ["linux-64"]
system-requirements = {cuda = "12"}

# List jax cuda depdency here as workaround Part 3 for https://github.com/prefix-dev/pixi/issues/1051
[tool.pixi.feature.jaxCuda.target.linux-64.pypi-dependencies]
"fftarray" = {version="*", extras=["jax"]}
"jax" = {version=">=0.4.30", extras=["cuda12"]}

[tool.pixi.environments]
jaxcuda = ["jaxCuda"]
# Recursive optional dependencies are currently ignored by pixi environments: https://github.com/prefix-dev/pixi/issues/2024
devcuda = ["dev", "jaxCuda", "pyFFTW", "helpers", "dashboards"]
dev = ["dev", "jax", "pyFFTW", "helpers", "dashboards"]
