name: Trigger Workflows via Comments

on:
  issue_comment:
    types: [created]

jobs:
  run-pip-test:
    if: |
      github.event.comment.body == '/run-pip' &&
      github.event.issue.pull_request != null
    runs-on: ubuntu-latest
    permissions:
      contents: read
      actions: write  # Required to dispatch workflows
    steps:
      - name: Trigger Tests
        uses: actions/create-workflow-dispatch@v1
        with:
          workflow_id: pip_test.yml  # Target workflow
          inputs: {}