name: Trigger Workflows via Comments

on:
  issue_comment:
    types: [created, edited, deleted]

jobs:
  run-job-a:
    runs-on: ubuntu-latest
    steps:
    - name: Install dependencies
      run: |
        echo "Hi a."