name: Test docs build via pixi

on:
  push:
    branches: [ "main" ]
  pull_request:

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    - uses: prefix-dev/setup-pixi@v0.8.1
      with:
        pixi-version: v0.34.0
        environments: ${{ matrix.environment }}
        cache: true
    # CPython 3.13 currently broken in CI due to pyfftw
    - run: pixi run -e doc312 doc
