name: Run full matrix pytest via pixi

on:
  push:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  test-full:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        environment: [check310, check311, check312, check313]
        command: [test_all, mypy]
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    - uses: prefix-dev/setup-pixi@v0.8.1
      with:
        pixi-version: v0.34.0
        environments: ${{ matrix.environment }}
        cache: true
    - run: pixi run -e ${{ matrix.environment }} ${{ matrix.command }}
